<a href="https://colab.research.google.com/github/Rashmika2004oshan/Database_Assesment/blob/main/Mongodb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Install Pymongo

In [ ]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.17.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 24.0 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 21.8 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.17.0

IMPORT LIBRARIES

In [ ]:
from pymongo import MongoClient
import pandas as pd

CONNECT TO MONGODB ATLAS

In [ ]:
import urllib.parse

username = urllib.parse.quote_plus("rashmikabandaraoshan2004_db_user")
password = urllib.parse.quote_plus("744U27y3aDb66Dq")

client = MongoClient(
    f"mongodb+srv://{username}:{password}@clusterassesment.q0ftt6z.mongodb.net/?appName=Clusterassesment"
)

db = client["northstar_db"]

UPLOAD DATASETS

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving app_events.csv to app_events.csv
Saving complaints.csv to complaints.csv
Saving customers.csv to customers.csv
Saving data_dictionary.csv to data_dictionary.csv
Saving deliveries.csv to deliveries.csv
Saving drivers.csv to drivers.csv
Saving hubs.csv to hubs.csv
Saving incidents.csv to incidents.csv
Saving vehicles.csv to vehicles.csv

LOAD DATASETS

In [ ]:
app_events = pd.read_csv("app_events.csv")

complaints = pd.read_csv("complaints.csv")

customers = pd.read_csv("customers.csv")

deliveries = pd.read_csv("deliveries.csv")

drivers = pd.read_csv("drivers.csv")

hubs = pd.read_csv("hubs.csv")

incidents = pd.read_csv("incidents.csv")

vehicles = pd.read_csv("vehicles.csv")

dictionary = pd.read_csv("data_dictionary.csv")

PREVIEW DATASETS

In [ ]:

incidents.head()

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,2024-03-11 23:46:00,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,2024-02-21 10:56:00,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,2025-04-17 23:22:00,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,2025-02-09 00:16:00,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,2025-01-04 02:49:00,Low,Open,13.0

In [ ]:
app_events.head()

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,2024-08-09 03:25:00,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,2024-02-13 22:29:00,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,2025-08-11 09:29:00,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,2025-08-23 17:38:00,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,2024-05-29 10:33:00,search_route,S12030,iOS,north,60,1

In [ ]:
vehicles.head()

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,NaN,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

CHECK MISSING VALUES

In [ ]:
print(app_events.isnull().sum())

print(incidents.isnull().sum())

print(vehicles.isnull().sum())

print(hubs.isnull().sum())

event_id             0
customer_id          0
order_id           144
event_timestamp      0
event_type           0
session_id           0
device_type          0
zone_context         0
api_latency_ms       0
success_flag         0
dtype: int64
incident_id           0
delivery_id           0
incident_type         0
reported_at           0
severity              0
resolution_status     0
resolved_hours       17
dtype: int64
vehicle_id            0
vehicle_type          0
assigned_zone         0
commission_date       0
battery_health_pct    4
odometer_km           0
maintenance_status    0
telematics_version    0
dtype: int64
hub_id            0
hub_name          0
zone              0
hub_type          0
capacity_score    0
dtype: int64

Clean dataset

In [ ]:
app_events = app_events.dropna()

incidents = incidents.dropna()

vehicles = vehicles.dropna()

hubs = hubs.dropna()

deliveries = deliveries.dropna()

complaints = complaints.dropna()

check after clean missing values

In [ ]:
print(app_events.isnull().sum())

print(incidents.isnull().sum())

print(vehicles.isnull().sum())

print(hubs.isnull().sum())

event_id           0
customer_id        0
order_id           0
event_timestamp    0
event_type         0
session_id         0
device_type        0
zone_context       0
api_latency_ms     0
success_flag       0
dtype: int64
incident_id          0
delivery_id          0
incident_type        0
reported_at          0
severity             0
resolution_status    0
resolved_hours       0
dtype: int64
vehicle_id            0
vehicle_type          0
assigned_zone         0
commission_date       0
battery_health_pct    0
odometer_km           0
maintenance_status    0
telematics_version    0
dtype: int64
hub_id            0
hub_name          0
zone              0
hub_type          0
capacity_score    0
dtype: int64

INSERT DATA INTO MONGODB

CONVERT TO DOCUMENTS

In [ ]:
app_docs = app_events.to_dict(
"records"
)

incident_docs = incidents.to_dict(
"records"
)

vehicle_docs = vehicles.to_dict(
"records"
)

hub_docs = hubs.to_dict(
"records"
)

delivery_docs = deliveries.to_dict(
"records"
)

complaint_docs = complaints.to_dict(
"records"
)

records after converting

In [ ]:
print(app_docs[:2])

print(incident_docs[:2])

print(vehicle_docs[:2])

print(hub_docs[:2])

[{'event_id': 'AE00002', 'customer_id': 'C0595', 'order_id': 'O00950', 'event_timestamp': '2024-02-13 22:29:00', 'event_type': 'search_route', 'session_id': 'S32766', 'device_type': 'Android', 'zone_context': 'SOUTH', 'api_latency_ms': 60, 'success_flag': 1}, {'event_id': 'AE00003', 'customer_id': 'C0494', 'order_id': 'O00170', 'event_timestamp': '2025-08-11 09:29:00', 'event_type': 'chat_opened', 'session_id': 'S99516', 'device_type': 'iOS', 'zone_context': 'Airport', 'api_latency_ms': 1118, 'success_flag': 1}]
[{'incident_id': 'I0001', 'delivery_id': 'DL00221', 'incident_type': 'BatteryAlert', 'reported_at': '2024-03-11 23:46:00', 'severity': 'Medium', 'resolution_status': 'Escalated', 'resolved_hours': 12.3}, {'incident_id': 'I0002', 'delivery_id': 'DL00578', 'incident_type': 'BatteryAlert', 'reported_at': '2024-02-21 10:56:00', 'severity': 'Low', 'resolution_status': 'Open', 'resolved_hours': 9.6}]
[{'vehicle_id': 'V001', 'vehicle_type': 'EV', 'assigned_zone': 'North', 'commission_date': '2024-12-28 23:48:00', 'battery_health_pct': 71.8, 'odometer_km': 56928, 'maintenance_status': 'Active', 'telematics_version': 'v2.2'}, {'vehicle_id': 'V002', 'vehicle_type': 'EV', 'assigned_zone': 'AIRPORT', 'commission_date': '2024-04-21 16:14:00', 'battery_health_pct': 67.9, 'odometer_km': 159368, 'maintenance_status': 'InRepair', 'telematics_version': 'v2.2'}]
[{'hub_id': 'H01', 'hub_name': 'North Exchange', 'zone': 'North', 'hub_type': 'Dispatch', 'capacity_score': 82}, {'hub_id': 'H02', 'hub_name': 'South Link', 'zone': 'South', 'hub_type': 'Dispatch', 'capacity_score': 78}]

Insert collection

In [ ]:
db.app_events.insert_many(app_docs)

db.incidents.insert_many(incident_docs)

db.vehicles.insert_many(vehicle_docs)

db.hubs.insert_many(hub_docs)

db.deliveries.insert_many(delivery_docs)

db.complaints.insert_many(complaint_docs)

InsertManyResult([ObjectId('6a05ba3f999bd8ec7a92c2ce'), ObjectId('6a05ba3f999bd8ec7a92c2cf'), ObjectId('6a05ba3f999bd8ec7a92c2d0'), ObjectId('6a05ba3f999bd8ec7a92c2d1'), ObjectId('6a05ba3f999bd8ec7a92c2d2'), ObjectId('6a05ba3f999bd8ec7a92c2d3'), ObjectId('6a05ba3f999bd8ec7a92c2d4'), ObjectId('6a05ba3f999bd8ec7a92c2d5'), ObjectId('6a05ba3f999bd8ec7a92c2d6'), ObjectId('6a05ba3f999bd8ec7a92c2d7'), ObjectId('6a05ba3f999bd8ec7a92c2d8'), ObjectId('6a05ba3f999bd8ec7a92c2d9'), ObjectId('6a05ba3f999bd8ec7a92c2da'), ObjectId('6a05ba3f999bd8ec7a92c2db'), ObjectId('6a05ba3f999bd8ec7a92c2dc'), ObjectId('6a05ba3f999bd8ec7a92c2dd'), ObjectId('6a05ba3f999bd8ec7a92c2de'), ObjectId('6a05ba3f999bd8ec7a92c2df'), ObjectId('6a05ba3f999bd8ec7a92c2e0'), ObjectId('6a05ba3f999bd8ec7a92c2e1'), ObjectId('6a05ba3f999bd8ec7a92c2e2'), ObjectId('6a05ba3f999bd8ec7a92c2e3'), ObjectId('6a05ba3f999bd8ec7a92c2e4'), ObjectId('6a05ba3f999bd8ec7a92c2e5'), ObjectId('6a05ba3f999bd8ec7a92c2e6'), ObjectId('6a05ba3f999bd8ec7a92c2e7'), ObjectId('6a05ba3f999bd8ec7a92c2e8'), ObjectId('6a05ba3f999bd8ec7a92c2e9'), ObjectId('6a05ba3f999bd8ec7a92c2ea'), ObjectId('6a05ba3f999bd8ec7a92c2eb'), ObjectId('6a05ba3f999bd8ec7a92c2ec'), ObjectId('6a05ba3f999bd8ec7a92c2ed'), ObjectId('6a05ba3f999bd8ec7a92c2ee'), ObjectId('6a05ba3f999bd8ec7a92c2ef'), ObjectId('6a05ba3f999bd8ec7a92c2f0'), ObjectId('6a05ba3f999bd8ec7a92c2f1'), ObjectId('6a05ba3f999bd8ec7a92c2f2'), ObjectId('6a05ba3f999bd8ec7a92c2f3'), ObjectId('6a05ba3f999bd8ec7a92c2f4'), ObjectId('6a05ba3f999bd8ec7a92c2f5'), ObjectId('6a05ba3f999bd8ec7a92c2f6'), ObjectId('6a05ba3f999bd8ec7a92c2f7'), ObjectId('6a05ba3f999bd8ec7a92c2f8'), ObjectId('6a05ba3f999bd8ec7a92c2f9'), ObjectId('6a05ba3f999bd8ec7a92c2fa'), ObjectId('6a05ba3f999bd8ec7a92c2fb'), ObjectId('6a05ba3f999bd8ec7a92c2fc'), ObjectId('6a05ba3f999bd8ec7a92c2fd'), ObjectId('6a05ba3f999bd8ec7a92c2fe'), ObjectId('6a05ba3f999bd8ec7a92c2ff'), ObjectId('6a05ba3f999bd8ec7a92c300'), ObjectId('6a05ba3f999bd8ec7a92c301'), ObjectId('6a05ba3f999bd8ec7a92c302'), ObjectId('6a05ba3f999bd8ec7a92c303'), ObjectId('6a05ba3f999bd8ec7a92c304'), ObjectId('6a05ba3f999bd8ec7a92c305'), ObjectId('6a05ba3f999bd8ec7a92c306'), ObjectId('6a05ba3f999bd8ec7a92c307'), ObjectId('6a05ba3f999bd8ec7a92c308'), ObjectId('6a05ba3f999bd8ec7a92c309'), ObjectId('6a05ba3f999bd8ec7a92c30a'), ObjectId('6a05ba3f999bd8ec7a92c30b'), ObjectId('6a05ba3f999bd8ec7a92c30c'), ObjectId('6a05ba3f999bd8ec7a92c30d'), ObjectId('6a05ba3f999bd8ec7a92c30e'), ObjectId('6a05ba3f999bd8ec7a92c30f'), ObjectId('6a05ba3f999bd8ec7a92c310'), ObjectId('6a05ba3f999bd8ec7a92c311'), ObjectId('6a05ba3f999bd8ec7a92c312'), ObjectId('6a05ba3f999bd8ec7a92c313'), ObjectId('6a05ba3f999bd8ec7a92c314'), ObjectId('6a05ba3f999bd8ec7a92c315'), ObjectId('6a05ba3f999bd8ec7a92c316'), ObjectId('6a05ba3f999bd8ec7a92c317'), ObjectId('6a05ba3f999bd8ec7a92c318'), ObjectId('6a05ba3f999bd8ec7a92c319'), ObjectId('6a05ba3f999bd8ec7a92c31a'), ObjectId('6a05ba3f999bd8ec7a92c31b'), ObjectId('6a05ba3f999bd8ec7a92c31c'), ObjectId('6a05ba3f999bd8ec7a92c31d'), ObjectId('6a05ba3f999bd8ec7a92c31e'), ObjectId('6a05ba3f999bd8ec7a92c31f'), ObjectId('6a05ba3f999bd8ec7a92c320'), ObjectId('6a05ba3f999bd8ec7a92c321'), ObjectId('6a05ba3f999bd8ec7a92c322'), ObjectId('6a05ba3f999bd8ec7a92c323'), ObjectId('6a05ba3f999bd8ec7a92c324'), ObjectId('6a05ba3f999bd8ec7a92c325'), ObjectId('6a05ba3f999bd8ec7a92c326'), ObjectId('6a05ba3f999bd8ec7a92c327'), ObjectId('6a05ba3f999bd8ec7a92c328'), ObjectId('6a05ba3f999bd8ec7a92c329'), ObjectId('6a05ba3f999bd8ec7a92c32a'), ObjectId('6a05ba3f999bd8ec7a92c32b'), ObjectId('6a05ba3f999bd8ec7a92c32c'), ObjectId('6a05ba3f999bd8ec7a92c32d'), ObjectId('6a05ba3f999bd8ec7a92c32e'), ObjectId('6a05ba3f999bd8ec7a92c32f'), ObjectId('6a05ba3f999bd8ec7a92c330'), ObjectId('6a05ba3f999bd8ec7a92c331'), ObjectId('6a05ba3f999bd8ec7a92c332'), ObjectId('6a05ba3f999bd8ec7a92c333'), ObjectId('6a05ba3f999bd8ec7a92c334'), ObjectId('6a05ba3f999bd8ec7a92c335'), ObjectId('6a05ba3f999bd8ec7a92c336'), ObjectId('6a05ba3f999bd8ec7a92c337'), ObjectId('6a05ba3f999bd8ec7a92c338'), ObjectId('6a05ba3f999bd8ec7a92c339'), ObjectId('6a05ba3f999bd8ec7a92c33a'), ObjectId('6a05ba3f999bd8ec7a92c33b'), ObjectId('6a05ba3f999bd8ec7a92c33c'), ObjectId('6a05ba3f999bd8ec7a92c33d'), ObjectId('6a05ba3f999bd8ec7a92c33e'), ObjectId('6a05ba3f999bd8ec7a92c33f'), ObjectId('6a05ba3f999bd8ec7a92c340'), ObjectId('6a05ba3f999bd8ec7a92c341'), ObjectId('6a05ba3f999bd8ec7a92c342'), ObjectId('6a05ba3f999bd8ec7a92c343'), ObjectId('6a05ba3f999bd8ec7a92c344'), ObjectId('6a05ba3f999bd8ec7a92c345'), ObjectId('6a05ba3f999bd8ec7a92c346'), ObjectId('6a05ba3f999bd8ec7a92c347'), ObjectId('6a05ba3f999bd8ec7a92c348'), ObjectId('6a05ba3f999bd8ec7a92c349'), ObjectId('6a05ba3f999bd8ec7a92c34a'), ObjectId('6a05ba3f999bd8ec7a92c34b'), ObjectId('6a05ba3f999bd8ec7a92c34c'), ObjectId('6a05ba3f999bd8ec7a92c34d'), ObjectId('6a05ba3f999bd8ec7a92c34e'), ObjectId('6a05ba3f999bd8ec7a92c34f'), ObjectId('6a05ba3f999bd8ec7a92c350'), ObjectId('6a05ba3f999bd8ec7a92c351'), ObjectId('6a05ba3f999bd8ec7a92c352'), ObjectId('6a05ba3f999bd8ec7a92c353'), ObjectId('6a05ba3f999bd8ec7a92c354'), ObjectId('6a05ba3f999bd8ec7a92c355'), ObjectId('6a05ba3f999bd8ec7a92c356'), ObjectId('6a05ba3f999bd8ec7a92c357'), ObjectId('6a05ba3f999bd8ec7a92c358'), ObjectId('6a05ba3f999bd8ec7a92c359'), ObjectId('6a05ba3f999bd8ec7a92c35a'), ObjectId('6a05ba3f999bd8ec7a92c35b'), ObjectId('6a05ba3f999bd8ec7a92c35c'), ObjectId('6a05ba3f999bd8ec7a92c35d'), ObjectId('6a05ba3f999bd8ec7a92c35e'), ObjectId('6a05ba3f999bd8ec7a92c35f'), ObjectId('6a05ba3f999bd8ec7a92c360'), ObjectId('6a05ba3f999bd8ec7a92c361'), ObjectId('6a05ba3f999bd8ec7a92c362'), ObjectId('6a05ba3f999bd8ec7a92c363'), ObjectId('6a05ba3f999bd8ec7a92c364'), ObjectId('6a05ba3f999bd8ec7a92c365'), ObjectId('6a05ba3f999bd8ec7a92c366'), ObjectId('6a05ba3f999bd8ec7a92c367'), ObjectId('6a05ba3f999bd8ec7a92c368'), ObjectId('6a05ba3f999bd8ec7a92c369'), ObjectId('6a05ba3f999bd8ec7a92c36a'), ObjectId('6a05ba3f999bd8ec7a92c36b'), ObjectId('6a05ba3f999bd8ec7a92c36c'), ObjectId('6a05ba3f999bd8ec7a92c36d'), ObjectId('6a05ba3f999bd8ec7a92c36e'), ObjectId('6a05ba3f999bd8ec7a92c36f'), ObjectId('6a05ba3f999bd8ec7a92c370'), ObjectId('6a05ba3f999bd8ec7a92c371'), ObjectId('6a05ba3f999bd8ec7a92c372'), ObjectId('6a05ba3f999bd8ec7a92c373'), ObjectId('6a05ba3f999bd8ec7a92c374'), ObjectId('6a05ba3f999bd8ec7a92c375'), ObjectId('6a05ba3f999bd8ec7a92c376'), ObjectId('6a05ba3f999bd8ec7a92c377'), ObjectId('6a05ba3f999bd8ec7a92c378'), ObjectId('6a05ba3f999bd8ec7a92c379'), ObjectId('6a05ba3f999bd8ec7a92c37a'), ObjectId('6a05ba3f999bd8ec7a92c37b'), ObjectId('6a05ba3f999bd8ec7a92c37c'), ObjectId('6a05ba3f999bd8ec7a92c37d'), ObjectId('6a05ba3f999bd8ec7a92c37e'), ObjectId('6a05ba3f999bd8ec7a92c37f'), ObjectId('6a05ba3f999bd8ec7a92c380'), ObjectId('6a05ba3f999bd8ec7a92c381'), ObjectId('6a05ba3f999bd8ec7a92c382'), ObjectId('6a05ba3f999bd8ec7a92c383'), ObjectId('6a05ba3f999bd8ec7a92c384'), ObjectId('6a05ba3f999bd8ec7a92c385'), ObjectId('6a05ba3f999bd8ec7a92c386'), ObjectId('6a05ba3f999bd8ec7a92c387'), ObjectId('6a05ba3f999bd8ec7a92c388'), ObjectId('6a05ba3f999bd8ec7a92c389'), ObjectId('6a05ba3f999bd8ec7a92c38a'), ObjectId('6a05ba3f999bd8ec7a92c38b'), ObjectId('6a05ba3f999bd8ec7a92c38c'), ObjectId('6a05ba3f999bd8ec7a92c38d'), ObjectId('6a05ba3f999bd8ec7a92c38e'), ObjectId('6a05ba3f999bd8ec7a92c38f'), ObjectId('6a05ba3f999bd8ec7a92c390'), ObjectId('6a05ba3f999bd8ec7a92c391'), ObjectId('6a05ba3f999bd8ec7a92c392'), ObjectId('6a05ba3f999bd8ec7a92c393'), ObjectId('6a05ba3f999bd8ec7a92c394'), ObjectId('6a05ba3f999bd8ec7a92c395'), ObjectId('6a05ba3f999bd8ec7a92c396'), ObjectId('6a05ba3f999bd8ec7a92c397'), ObjectId('6a05ba3f999bd8ec7a92c398'), ObjectId('6a05ba3f999bd8ec7a92c399'), ObjectId('6a05ba3f999bd8ec7a92c39a'), ObjectId('6a05ba3f999bd8ec7a92c39b'), ObjectId('6a05ba3f999bd8ec7a92c39c'), ObjectId('6a05ba3f999bd8ec7a92c39d'), ObjectId('6a05ba3f999bd8ec7a92c39e'), ObjectId('6a05ba3f999bd8ec7a92c39f'), ObjectId('6a05ba3f999bd8ec7a92c3a0'), ObjectId('6a05ba3f999bd8ec7a92c3a1'), ObjectId('6a05ba3f999bd8ec7a92c3a2'), ObjectId('6a05ba3f999bd8ec7a92c3a3'), ObjectId('6a05ba3f999bd8ec7a92c3a4'), ObjectId('6a05ba3f999bd8ec7a92c3a5'), ObjectId('6a05ba3f999bd8ec7a92c3a6'), ObjectId('6a05ba3f999bd8ec7a92c3a7'), ObjectId('6a05ba3f999bd8ec7a92c3a8'), ObjectId('6a05ba3f999bd8ec7a92c3a9'), ObjectId('6a05ba3f999bd8ec7a92c3aa'), ObjectId('6a05ba3f999bd8ec7a92c3ab'), ObjectId('6a05ba3f999bd8ec7a92c3ac'), ObjectId('6a05ba3f999bd8ec7a92c3ad'), ObjectId('6a05ba3f999bd8ec7a92c3ae'), ObjectId('6a05ba3f999bd8ec7a92c3af'), ObjectId('6a05ba3f999bd8ec7a92c3b0'), ObjectId('6a05ba3f999bd8ec7a92c3b1'), ObjectId('6a05ba3f999bd8ec7a92c3b2'), ObjectId('6a05ba3f999bd8ec7a92c3b3'), ObjectId('6a05ba3f999bd8ec7a92c3b4'), ObjectId('6a05ba3f999bd8ec7a92c3b5'), ObjectId('6a05ba3f999bd8ec7a92c3b6'), ObjectId('6a05ba3f999bd8ec7a92c3b7'), ObjectId('6a05ba3f999bd8ec7a92c3b8'), ObjectId('6a05ba3f999bd8ec7a92c3b9'), ObjectId('6a05ba3f999bd8ec7a92c3ba'), ObjectId('6a05ba3f999bd8ec7a92c3bb'), ObjectId('6a05ba3f999bd8ec7a92c3bc'), ObjectId('6a05ba3f999bd8ec7a92c3bd'), ObjectId('6a05ba3f999bd8ec7a92c3be'), ObjectId('6a05ba3f999bd8ec7a92c3bf'), ObjectId('6a05ba3f999bd8ec7a92c3c0'), ObjectId('6a05ba3f999bd8ec7a92c3c1'), ObjectId('6a05ba3f999bd8ec7a92c3c2'), ObjectId('6a05ba3f999bd8ec7a92c3c3'), ObjectId('6a05ba3f999bd8ec7a92c3c4'), ObjectId('6a05ba3f999bd8ec7a92c3c5'), ObjectId('6a05ba3f999bd8ec7a92c3c6'), ObjectId('6a05ba3f999bd8ec7a92c3c7'), ObjectId('6a05ba3f999bd8ec7a92c3c8'), ObjectId('6a05ba3f999bd8ec7a92c3c9'), ObjectId('6a05ba3f999bd8ec7a92c3ca'), ObjectId('6a05ba3f999bd8ec7a92c3cb'), ObjectId('6a05ba3f999bd8ec7a92c3cc'), ObjectId('6a05ba3f999bd8ec7a92c3cd'), ObjectId('6a05ba3f999bd8ec7a92c3ce'), ObjectId('6a05ba3f999bd8ec7a92c3cf'), ObjectId('6a05ba3f999bd8ec7a92c3d0'), ObjectId('6a05ba3f999bd8ec7a92c3d1'), ObjectId('6a05ba3f999bd8ec7a92c3d2'), ObjectId('6a05ba3f999bd8ec7a92c3d3'), ObjectId('6a05ba3f999bd8ec7a92c3d4'), ObjectId('6a05ba3f999bd8ec7a92c3d5'), ObjectId('6a05ba3f999bd8ec7a92c3d6'), ObjectId('6a05ba3f999bd8ec7a92c3d7'), ObjectId('6a05ba3f999bd8ec7a92c3d8'), ObjectId('6a05ba3f999bd8ec7a92c3d9'), ObjectId('6a05ba3f999bd8ec7a92c3da'), ObjectId('6a05ba3f999bd8ec7a92c3db'), ObjectId('6a05ba3f999bd8ec7a92c3dc'), ObjectId('6a05ba3f999bd8ec7a92c3dd'), ObjectId('6a05ba3f999bd8ec7a92c3de'), ObjectId('6a05ba3f999bd8ec7a92c3df'), ObjectId('6a05ba3f999bd8ec7a92c3e0'), ObjectId('6a05ba3f999bd8ec7a92c3e1'), ObjectId('6a05ba3f999bd8ec7a92c3e2'), ObjectId('6a05ba3f999bd8ec7a92c3e3'), ObjectId('6a05ba3f999bd8ec7a92c3e4'), ObjectId('6a05ba3f999bd8ec7a92c3e5'), ObjectId('6a05ba3f999bd8ec7a92c3e6'), ObjectId('6a05ba3f999bd8ec7a92c3e7'), ObjectId('6a05ba3f999bd8ec7a92c3e8'), ObjectId('6a05ba3f999bd8ec7a92c3e9'), ObjectId('6a05ba3f999bd8ec7a92c3ea'), ObjectId('6a05ba3f999bd8ec7a92c3eb'), ObjectId('6a05ba3f999bd8ec7a92c3ec'), ObjectId('6a05ba3f999bd8ec7a92c3ed'), ObjectId('6a05ba3f999bd8ec7a92c3ee'), ObjectId('6a05ba3f999bd8ec7a92c3ef'), ObjectId('6a05ba3f999bd8ec7a92c3f0'), ObjectId('6a05ba3f999bd8ec7a92c3f1'), ObjectId('6a05ba3f999bd8ec7a92c3f2'), ObjectId('6a05ba3f999bd8ec7a92c3f3'), ObjectId('6a05ba3f999bd8ec7a92c3f4'), ObjectId('6a05ba3f999bd8ec7a92c3f5'), ObjectId('6a05ba3f999bd8ec7a92c3f6'), ObjectId('6a05ba3f999bd8ec7a92c3f7'), ObjectId('6a05ba3f999bd8ec7a92c3f8'), ObjectId('6a05ba3f999bd8ec7a92c3f9'), ObjectId('6a05ba3f999bd8ec7a92c3fa'), ObjectId('6a05ba3f999bd8ec7a92c3fb'), ObjectId('6a05ba3f999bd8ec7a92c3fc'), ObjectId('6a05ba3f999bd8ec7a92c3fd')], acknowledged=True)

CRUD OPERATIONS

 CREATE DOCUMENT

In [ ]:
result = db.vehicles.insert_one({

"vehicle_id":"V999",

"status":"maintenance",

"city":"London"

})

Read Documents

In [ ]:

last_10_vehicles = db.vehicles.find().sort('_id', -1).limit(10)

for vehicle in last_10_vehicles:
   print(vehicle)

{'_id': ObjectId('6a05bc28999bd8ec7a92c3fe'), 'vehicle_id': 'V999', 'status': 'maintenance', 'city': 'London'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf30'), 'vehicle_id': 'V120', 'vehicle_type': 'EV', 'assigned_zone': 'CENTRAL', 'commission_date': '2025-05-02 16:13:00', 'battery_health_pct': 73.6, 'odometer_km': 192246, 'maintenance_status': 'Active', 'telematics_version': 'v2.0'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf2f'), 'vehicle_id': 'V119', 'vehicle_type': 'EV', 'assigned_zone': 'RiverSide', 'commission_date': '2025-08-17 06:19:00', 'battery_health_pct': 67.6, 'odometer_km': 215407, 'maintenance_status': 'InRepair', 'telematics_version': 'v2.1'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf2e'), 'vehicle_id': 'V118', 'vehicle_type': 'Diesel', 'assigned_zone': 'Riverside', 'commission_date': '2025-02-18 12:40:00', 'battery_health_pct': 78.0, 'odometer_km': 145165, 'maintenance_status': 'Active', 'telematics_version': 'v2.1'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf2d'), 'vehicle_id': 'V117', 'vehicle_type': 'Hybrid', 'assigned_zone': 'SOUTH', 'commission_date': '2025-01-11 11:13:00', 'battery_health_pct': 65.5, 'odometer_km': 163683, 'maintenance_status': 'Scheduled', 'telematics_version': 'v2.2'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf2c'), 'vehicle_id': 'V116', 'vehicle_type': 'Diesel', 'assigned_zone': 'EAST', 'commission_date': '2025-04-23 07:10:00', 'battery_health_pct': 62.7, 'odometer_km': 71822, 'maintenance_status': 'Active', 'telematics_version': 'v2.1'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf2b'), 'vehicle_id': 'V115', 'vehicle_type': 'Diesel', 'assigned_zone': 'South', 'commission_date': '2024-05-10 17:28:00', 'battery_health_pct': 57.9, 'odometer_km': 85919, 'maintenance_status': 'Active', 'telematics_version': 'v2.2'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf2a'), 'vehicle_id': 'V114', 'vehicle_type': 'Hybrid', 'assigned_zone': 'North', 'commission_date': '2024-10-03 17:53:00', 'battery_health_pct': 90.0, 'odometer_km': 84649, 'maintenance_status': 'Active', 'telematics_version': 'v2.2'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf29'), 'vehicle_id': 'V113', 'vehicle_type': 'Hybrid', 'assigned_zone': 'Central', 'commission_date': '2024-05-12 02:12:00', 'battery_health_pct': 58.9, 'odometer_km': 52725, 'maintenance_status': 'InRepair', 'telematics_version': 'v1.9'}
{'_id': ObjectId('6a05ba3b999bd8ec7a92bf28'), 'vehicle_id': 'V112', 'vehicle_type': 'EV', 'assigned_zone': 'South', 'commission_date': '2024-06-08 07:45:00', 'battery_health_pct': 94.1, 'odometer_km': 19121, 'maintenance_status': 'InRepair', 'telematics_version': 'v2.1'}

 UPDATE DOCUMENT

In [ ]:
db.vehicles.update_one(

{"vehicle_id":"V999"},

{"$set":{"status":"active"}}

)

UpdateResult({'n': 1, 'electionId': ObjectId('7fffffff0000000000000251'), 'opTime': {'ts': Timestamp(1778760994, 233), 't': 593}, 'nModified': 1, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1778760994, 233), 'signature': {'hash': b'C\\~9\\0TQ\n\xb4h\x061GVP\xf0\x843j', 'keyId': 7594618677551431681}}, 'operationTime': Timestamp(1778760994, 233), 'updatedExisting': True}, acknowledged=True)

DELETE DOCUMENT

In [ ]:
db.vehicles.delete_one({

"vehicle_id":"V999"

})

DeleteResult({'n': 1, 'electionId': ObjectId('7fffffff0000000000000251'), 'opTime': {'ts': Timestamp(1778761017, 183), 't': 593}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1778761017, 183), 'signature': {'hash': b'\x02@\x1a\xbb\x15\n\x15\x01\x8do\x11\x8f\x8c\xe2\xca\x15ky\t\xb5', 'keyId': 7594618677551431681}}, 'operationTime': Timestamp(1778761017, 183)}, acknowledged=True)

In [ ]:
deleted_doc = db.vehicles.find_one({"vehicle_id": "V999"})
if deleted_doc is None:
    print(f" Document with vehicle_id 'V999' successfully deleted.")
else:
    print(f" Document with vehicle_id 'V999' still exists: {deleted_doc}")

 Document with vehicle_id 'V999' successfully deleted.

AGGREGATION ANALYSIS

APP EVENT ANALYSIS

In [ ]:
pipeline = [

{
"$group":
{
"_id":"$event_type",
"count":{"$sum":1}
}
}

]

list(db.app_events.aggregate(pipeline))

[{'_id': 'payment_retry', 'count': 53},
 {'_id': 'cancel_attempt', 'count': 20},
 {'_id': 'chat_escalated', 'count': 29},
 {'_id': 'eta_refresh', 'count': 83},
 {'_id': 'search_route', 'count': 79},
 {'_id': 'track_order', 'count': 106},
 {'_id': 'chat_opened', 'count': 67},
 {'_id': 'delivery_instruction_update', 'count': 59}]

INCIDENT ANALYSIS

In [ ]:
pipeline = [

{
"$group":
{
"_id":"$incident_type",
"count":{"$sum":1}
}
}

]

list(db.incidents.aggregate(pipeline))

[{'_id': 'BatteryAlert', 'count': 34},
 {'_id': 'AppSyncError', 'count': 28},
 {'_id': 'RouteDeviation', 'count': 41},
 {'_id': 'VehicleFault', 'count': 36},
 {'_id': 'SafetyNearMiss', 'count': 13},
 {'_id': 'ProofMissing', 'count': 40},
 {'_id': 'TemperatureIssue', 'count': 29},
 {'_id': 'CustomerNoShow', 'count': 42}]

HUB PERFORMANCE ANALYSIS

In [ ]:
pipeline = [

{
"$group":
{
"_id":"$hub_id",
"avg_utilisation":
{
"$avg":"$utilisation_rate"
}
}
}

]

list(db.hubs.aggregate(pipeline))

[{'_id': 'H01', 'avg_utilisation': None},
 {'_id': 'H07', 'avg_utilisation': None},
 {'_id': 'H02', 'avg_utilisation': None},
 {'_id': 'H04', 'avg_utilisation': None},
 {'_id': 'H08', 'avg_utilisation': None},
 {'_id': 'H05', 'avg_utilisation': None},
 {'_id': 'H06', 'avg_utilisation': None},
 {'_id': 'H03', 'avg_utilisation': None}]

VEHICLE ANALYSIS

In [ ]:
pipeline = [

{
"$group":
{
"_id":"$status",
"count":{"$sum":1}
}
}

]

list(db.vehicles.aggregate(pipeline))

[{'_id': None, 'count': 116}]

DELIVERY FAILURE ANALYSIS

In [ ]:
pipeline = [

{
"$group":
{
"_id":"$delivery_status",
"count":{"$sum":1}
}
}

]

list(db.deliveries.aggregate(pipeline))

[{'_id': 'Failed', 'count': 260},
 {'_id': 'OnTime', 'count': 1212},
 {'_id': 'Delayed', 'count': 395}]

INSERT NESTED DOCUMENT

In [ ]:
db.customer_cases.insert_one({

"customer_id":1001,

"case_history":[

{
"message":"Late delivery",
"status":"open"
},

{
"message":"Driver contacted",
"status":"resolved"
}

],

"app_events":[

{
"type":"tracking",
"time":"10:00"
},

{
"type":"complaint",
"time":"10:30"
}

]

})

InsertOneResult(ObjectId('6a05cca4999bd8ec7a92c3ff'), acknowledged=True)

QUERY OPTIMISATION

CREATE INDEXES

In [ ]:
db.vehicles.create_index(
[("vehicle_id",1)]
)

db.incidents.create_index(
[("incident_type",1)]
)

db.app_events.create_index(
[("event_type",1)]
)

'event_type_1'